### ISSUE TITLE
Worth adding OPML file?

### ISSUE THREAD

**Issue by nitinthewiz** [m8/refined.blog#18]
I understand that the idea is individual personal blogs, but the tags are only ever so useful. Does it make sense to add one or more OPML feed links so people can subscribe to all/some of the blogs on the site?

**Comment by m8** [comment]
yes, you're right we can make opml export for selected blogs. also, i think it's possible in datatables. thanks for the idea. i will look this on weekend.

**Comment by m8** [comment]
Hey, I added OPML export for selected blogs and you can directly subscribe with your rss reader. thanks for the idea

**Comment by nitinthewiz** [comment]
That's awesome! Thanks so much!

**Comment by nitinthewiz** [comment]
That is a BRILLIANT implementation! Love the multi-select feature...
